# Generated by Django 3.2.8 on 2021-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lilabapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='monto_credito',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
